[package]
name = "chatapp"
version = "0.1.0"
author = "Ronak Harkhani"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }